from typing import Callable

class WindowHandle:
    def __init__(self) -> None: ...
    async def set_title(self, new_title: str) -> str: ...
    async def get_title(self) -> str: ...


def create_webframe(handler:Callable, html: str):...